### ISSUE TITLE
Auth constructor with provider argument cause RPC call errors

### ISSUE THREAD

**Issue by fdelosriossanchez** [ConsenSys/infura-sdk#117]
**Describe the bug**
When instantiating an Auth class as an argument for an SDK instance, SDK calls cause RPC errors. This seems to be produced by the fact Auth constructor calls Provider.getInjectedProvider with argument provider. I tried with several ethers.providers, including InfuraProvider, and all cause the same problem: RPC call method key contains the whole payload object instead of just the method:

This call: `{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":83}`
Turns into this call and fails: `{"jsonrpc":"2.0","method":"{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":83}","params":[],"id":83}`

I managed to presumably fix it by getInjectedProvider method in Provider.js return value:

From: `return new ethers.providers.Web3Provider(injectedProvider);`
To: `return injectedProvider;`

Not sure if it breaks something else, but it works for me.

**To Reproduce**
`import { config } from 'dotenv'
import { SDK, Auth } from '@infura/sdk'
import { ethers } from 'ethers'

config()
const { INFURA_KEY, INFURA_SECRET, NETWORK } = process.env

const provider = new ethers.providers.InfuraProvider(NETWORK, INFURA_KEY)

const auth = new Auth({ projectId: INFURA_KEY, secretId: INFURA_SECRET, provider, chainId: provider.network.chainId })
const sdk = new SDK(auth)

export const listNFTsMetadata = async (owner) => {
  const rawNFTs = await sdk.getNFTs({ publicAddress: owner, includeMetadata: true })
  const metadata = rawNFTs.assets.map(x => x.metadata).filter(x => x !== null).map(({ image, name, description }) => ({ image, name, description }))
}`

Call listNFTsMetadata throws an RPC error.

**Expected behavior**
No RPC errors should happen if RPC server is available.

**Screenshots or code block**
\node_modules\@infura\sdk\src\lib\Provider\Provider.js[getInjectedProvider]

**Comment by danielpavelicconsensys** [comment]
Hi @fdelosriossanchez, 
thanks for reporting the issue, we'll take a look and provide feedback.

Thank you

**Comment by salimtb** [comment]
Hi @fdelosriossanchez ,
a fix for the problem you have reported is pushed in production, for the moment we can not allow the infura provider because it can’t sign ( there is no private key associated with this provider ), however the error message has been improved to make it more explicit
