### ISSUE TITLE
typescript binding issue when calling API in nextjs

### ISSUE THREAD

**Issue by jpzhangvincent** [ConsenSys/infura-sdk#177]
**Describe the bug**
Typescript error when importing the package in an API script for nextjs. It seems the API can't be triggered.

**To Reproduce**
1. working on my project chatGPT prompt minting tool - [repo](https://github.com/jpzhangvincent/chatbot-ui/tree/jp-experiment)
3. I have a [script](https://github.com/jpzhangvincent/chatbot-ui/blob/jp-experiment/pages/api/mintNFT.ts) for `minting NFT` under the `pages/api` with the nextjs framework 
4. launch the app with `npm dev run` and then click the `create a prompt` to get the Prompt modal view 
<img width="505" alt="Screenshot 2023-04-07 at 2 39 13 PM" src="https://user-images.githubusercontent.com/7220686/230682225-9fd8ba9c-6280-4773-90cd-ee1346abc1a9.png">
5. after filling some dummy data, clicking the `mint NFT` button on the UI which should trigger the `handleMintPrompt` function in the [index.tsx](https://github.com/jpzhangvincent/chatbot-ui/blob/jp-experiment/pages/index.tsx). Got the API error from the server side showed in the terminal

```shell
error - node_modules/ipfs-utils/src/http.js (6:0) @ <unknown>
error - __webpack_require__(...).bind is not a function
``` 

**Expected behavior**
 I had made sure all the credentials working and added in the `.env` under the root. The expected outcome is to be able to mint the prompt text as NFT. (it seems image url is required (not sure why?) but just put dummy link there) 

**Screenshots or code block**
 I also tested the api logic with the following script under the project root, it's working fine - 
 
```typescript
import { config as loadEnv } from 'dotenv';
import { SDK, Auth, Metadata, TEMPLATES } from '@infura/sdk';

loadEnv();

const name = 'test'
const description = 'testing'
const prompt = 'testing'
const walletAddress = '...'

try {
        const auth = new Auth({
            projectId: process.env.INFURA_API_KEY,
            secretId: process.env.INFURA_API_KEY_SECRET,
            privateKey: process.env.WALLET_PRIVATE_KEY,
            rpcUrl: process.env.RPC_URL,
            chainId: 80001, // Mumbai
            ipfs: {
              projectId: process.env.INFURA_IPFS_PROJECT_ID,
              apiKeySecret: process.env.INFURA_IPFS_PROJECT_SECRET,
            }
          });
        
        const sdk = new SDK(auth);

        console.log(sdk)

        const contractAddress = '0xDA7358Ba86b51A6C7FE7033F9400F0fdFa356c5d'

        const contract = await sdk.loadContract({
         template: TEMPLATES.ERC721Mintable,
         contractAddress
        })

        // CREATE Token Metadata
        const tokenMetadata = Metadata.openSeaTokenLevelStandard({
            name: `${name}`,
            description: `${description}`,
            external_url: 'https://d2q0omy5xtz2zh.cloudfront.net/hero/prompt-builder-v0-2-0.webp',
            image: 'https://res.cloudinary.com/practicaldev/image/fetch/s--a9dULhJ6--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/8ww354qlpdypw5ohs7s2.png',
            attributes: [{
                "trait_type": "Prompt", 
                "value": `${prompt}`
              }],
        });
        
        console.log(tokenMetadata)

        // mint a NFT
        const mint = await contract.mint({
            publicAddress: process.env.WALLET_PUBLIC_ADDRESS ?? walletAddress,
            tokenURI: tokenMetadata,
        });
  
        const minted = await mint.wait();
        console.log(minted)
        return new Response(minted, { status: 200 })
    } catch (error) {
        console.log("testing")
        console.log(error);
      return new Response(JSON.stringify(error), { status: 500 });
    }
``` 

<img width="901" alt="Screenshot 2023-04-07 at 2 43 23 PM" src="https://user-images.githubusercontent.com/7220686/230682591-6c0a20b7-f28f-4ae6-8183-9aa60b69b56b.png">

**Additional context**
I have a [script](https://github.com/jpzhangvincent/chatbot-ui/blob/jp-experiment/deployNFTcontract.mjs) and ran it before to deploy the contract with the SDK which returns the contract address - `0xDA7358Ba86b51A6C7FE7033F9400F0fdFa356c5d` so the app logic only needs to handle the minting logic.I deployed on the Polygon Mumbai testnet.

**Comment by salimtb** [comment]
hello @jpzhangvincent
thank you for reporting this problem, we will start working on its resolution and keep you informed

**Comment by salimtb** [comment]
hey @jpzhangvincent 
after a quick investigation , i noticed that the issue is related to the package` ipfs-http-client` ( a dependency that we are using in our package ).but it seems that this problem is known and that there is already an open issue for it [here](https://github.com/ipfs/js-ipfs/issues/3452) 
i'm going to open another one and try to push them for a solution

**Comment by salimtb** [comment]
hey @jpzhangvincent ,
the version 2.4.1 was just published , the issue was resolved
